CREATE SCHEMA SWIMA AUTHORIZATION ADMIN;    

create table SWIMA.EQUITY (  
    ID INTEGER primary key,  
    SYMBOL VARCHAR(10),
    NAME VARCHAR(50)
);

create table SWIMA.PRICE (  
    EQUITY INTEGER not null,
    TRADE_DT DATE not null,
    PRICE_OPEN FLOAT,
    PRICE_LOW FLOAT,
    PRICE_CLOSE FLOAT,
    PRICE_ADJ FLOAT,
    TRADE_VOLUMN INTEGER
);

ALTER TABLE SWIMA.PRICE ADD CONSTRAINT PRICE_PRIMARY_KEY PRIMARY KEY (EQUITY, TRADE_DT);
ALTER TABLE SWIMA.PRICE ADD CONSTRAINT PRICE_EQUITY_FOREIGN_KEY FOREIGN KEY(EQUITY) REFERENCES SWIMA.EQUITY(ID);
