delete from APP.HDB_TOWN;
insert into APP.HDB_TOWN (id, name) values (1,'Ang Mo Kio');
insert into APP.HDB_TOWN (id, name) values (2,'Bedok');
insert into APP.HDB_TOWN (id, name) values (3,'Bishan');
insert into APP.HDB_TOWN (id, name) values (4,'Bukit Batok');
insert into APP.HDB_TOWN (id, name) values (5,'Bukit Merah');
insert into APP.HDB_TOWN (id, name) values (6,'Bukit Panjang');
insert into APP.HDB_TOWN (id, name) values (7,'Bukit Timah');
insert into APP.HDB_TOWN (id, name) values (8,'Central Area');
insert into APP.HDB_TOWN (id, name) values (9,'Choa Chu Kang');
insert into APP.HDB_TOWN (id, name) values (10,'Clementi');
insert into APP.HDB_TOWN (id, name) values (11,'Geylang');
insert into APP.HDB_TOWN (id, name) values (12,'Hougang');
insert into APP.HDB_TOWN (id, name) values (13,'Jurong East');
insert into APP.HDB_TOWN (id, name) values (14,'Jurong West');
insert into APP.HDB_TOWN (id, name) values (15,'Kallang/Whampoa');
insert into APP.HDB_TOWN (id, name) values (16,'Lim Chu Kang');
insert into APP.HDB_TOWN (id, name) values (17,'Marine Parade');
insert into APP.HDB_TOWN (id, name) values (18,'Pasir Ris');
insert into APP.HDB_TOWN (id, name) values (19,'Punggol');
insert into APP.HDB_TOWN (id, name) values (20,'Queenstown');
insert into APP.HDB_TOWN (id, name) values (21,'Sembawang');
insert into APP.HDB_TOWN (id, name) values (22,'Sengkang');
insert into APP.HDB_TOWN (id, name) values (23,'Serangoon');
insert into APP.HDB_TOWN (id, name) values (24,'Tampines');
insert into APP.HDB_TOWN (id, name) values (25,'Toa Payoh');
insert into APP.HDB_TOWN (id, name) values (26,'Woodlands');
insert into APP.HDB_TOWN (id, name) values (27,'Yishun');

delete from APP.HDB_TYPE;
insert into APP.HDB_TYPE(ref,name) values ('01','1 Room');
insert into APP.HDB_TYPE(ref,name) values ('02','2 Room');
insert into APP.HDB_TYPE(ref,name) values ('03','3 Room');
insert into APP.HDB_TYPE(ref,name) values ('04','4 Room');
insert into APP.HDB_TYPE(ref,name) values ('05','5 Room');
insert into APP.HDB_TYPE(ref,name) values ('06','Executive');
insert into APP.HDB_TYPE(ref,name) values ('07','HUDC');
insert into APP.HDB_TYPE(ref,name) values ('08','Multi-Generation');

